// Generated by gencpp from file yumi_scripts/JointMsg.msg
// DO NOT EDIT!


#ifndef YUMI_SCRIPTS_MESSAGE_JOINTMSG_H
#define YUMI_SCRIPTS_MESSAGE_JOINTMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yumi_scripts
{
template <class ContainerAllocator>
struct JointMsg_
{
  typedef JointMsg_<ContainerAllocator> Type;

  JointMsg_()
    : joint_values()  {
    }
  JointMsg_(const ContainerAllocator& _alloc)
    : joint_values(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joint_values_type;
  _joint_values_type joint_values;





  typedef boost::shared_ptr< ::yumi_scripts::JointMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yumi_scripts::JointMsg_<ContainerAllocator> const> ConstPtr;

}; // struct JointMsg_

typedef ::yumi_scripts::JointMsg_<std::allocator<void> > JointMsg;

typedef boost::shared_ptr< ::yumi_scripts::JointMsg > JointMsgPtr;
typedef boost::shared_ptr< ::yumi_scripts::JointMsg const> JointMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yumi_scripts::JointMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yumi_scripts::JointMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yumi_scripts

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'yumi_scripts': ['/home/yumi/yumi_ws/src/yumi/yumi_scripts/msg'], 'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/kinetic/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/kinetic/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yumi_scripts::JointMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yumi_scripts::JointMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yumi_scripts::JointMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yumi_scripts::JointMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yumi_scripts::JointMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yumi_scripts::JointMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yumi_scripts::JointMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b79b974a6ae3f399e6d798ff6613e367";
  }

  static const char* value(const ::yumi_scripts::JointMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb79b974a6ae3f399ULL;
  static const uint64_t static_value2 = 0xe6d798ff6613e367ULL;
};

template<class ContainerAllocator>
struct DataType< ::yumi_scripts::JointMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yumi_scripts/JointMsg";
  }

  static const char* value(const ::yumi_scripts::JointMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yumi_scripts::JointMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] joint_values\n\
";
  }

  static const char* value(const ::yumi_scripts::JointMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yumi_scripts::JointMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yumi_scripts::JointMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yumi_scripts::JointMsg_<ContainerAllocator>& v)
  {
    s << indent << "joint_values[]" << std::endl;
    for (size_t i = 0; i < v.joint_values.size(); ++i)
    {
      s << indent << "  joint_values[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YUMI_SCRIPTS_MESSAGE_JOINTMSG_H
