// Generated by gencpp from file yumi_scripts/PoseConfigMsg.msg
// DO NOT EDIT!


#ifndef YUMI_SCRIPTS_MESSAGE_POSECONFIGMSG_H
#define YUMI_SCRIPTS_MESSAGE_POSECONFIGMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace yumi_scripts
{
template <class ContainerAllocator>
struct PoseConfigMsg_
{
  typedef PoseConfigMsg_<ContainerAllocator> Type;

  PoseConfigMsg_()
    : group_name()
    , pose()
    , confdata()
    , external_axis_position(0.0)
    , gripper_attached(false)
    , gripper_position(0.0)  {
    }
  PoseConfigMsg_(const ContainerAllocator& _alloc)
    : group_name(_alloc)
    , pose(_alloc)
    , confdata(_alloc)
    , external_axis_position(0.0)
    , gripper_attached(false)
    , gripper_position(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _group_name_type;
  _group_name_type group_name;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _confdata_type;
  _confdata_type confdata;

   typedef double _external_axis_position_type;
  _external_axis_position_type external_axis_position;

   typedef uint8_t _gripper_attached_type;
  _gripper_attached_type gripper_attached;

   typedef double _gripper_position_type;
  _gripper_position_type gripper_position;





  typedef boost::shared_ptr< ::yumi_scripts::PoseConfigMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yumi_scripts::PoseConfigMsg_<ContainerAllocator> const> ConstPtr;

}; // struct PoseConfigMsg_

typedef ::yumi_scripts::PoseConfigMsg_<std::allocator<void> > PoseConfigMsg;

typedef boost::shared_ptr< ::yumi_scripts::PoseConfigMsg > PoseConfigMsgPtr;
typedef boost::shared_ptr< ::yumi_scripts::PoseConfigMsg const> PoseConfigMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yumi_scripts::PoseConfigMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yumi_scripts::PoseConfigMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yumi_scripts

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'yumi_scripts': ['/home/yumi/yumi_ws/src/yumi/yumi_scripts/msg'], 'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/kinetic/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/kinetic/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yumi_scripts::PoseConfigMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yumi_scripts::PoseConfigMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yumi_scripts::PoseConfigMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yumi_scripts::PoseConfigMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yumi_scripts::PoseConfigMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yumi_scripts::PoseConfigMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yumi_scripts::PoseConfigMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45da748a00accc427392a77b8503106f";
  }

  static const char* value(const ::yumi_scripts::PoseConfigMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45da748a00accc42ULL;
  static const uint64_t static_value2 = 0x7392a77b8503106fULL;
};

template<class ContainerAllocator>
struct DataType< ::yumi_scripts::PoseConfigMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yumi_scripts/PoseConfigMsg";
  }

  static const char* value(const ::yumi_scripts::PoseConfigMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yumi_scripts::PoseConfigMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string group_name\n\
geometry_msgs/Pose pose\n\
int32[] confdata\n\
float64 external_axis_position\n\
bool gripper_attached\n\
float64 gripper_position\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::yumi_scripts::PoseConfigMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yumi_scripts::PoseConfigMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.group_name);
      stream.next(m.pose);
      stream.next(m.confdata);
      stream.next(m.external_axis_position);
      stream.next(m.gripper_attached);
      stream.next(m.gripper_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseConfigMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yumi_scripts::PoseConfigMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yumi_scripts::PoseConfigMsg_<ContainerAllocator>& v)
  {
    s << indent << "group_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.group_name);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "confdata[]" << std::endl;
    for (size_t i = 0; i < v.confdata.size(); ++i)
    {
      s << indent << "  confdata[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.confdata[i]);
    }
    s << indent << "external_axis_position: ";
    Printer<double>::stream(s, indent + "  ", v.external_axis_position);
    s << indent << "gripper_attached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gripper_attached);
    s << indent << "gripper_position: ";
    Printer<double>::stream(s, indent + "  ", v.gripper_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YUMI_SCRIPTS_MESSAGE_POSECONFIGMSG_H
